# Generated by Django 3.2 on 2021-04-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_salmon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="splatnet_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="splatNet 2 JSON file"
            ),
        ),
    ]
