runtime: python38
entrypoint: gunicorn -b :$PORT <your app name>.wsgi

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/