# Generated by Django 3.2 on 2021-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("splatnet_id", models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "splatnet_json",
                    models.JSONField(blank=True, verbose_name="splatNet 2 JSON file"),
                ),
                (
                    "stat_ink_json",
                    models.JSONField(blank=True, verbose_name="stat.ink JSON file"),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("splat_zones", "Splat Zones"),
                            ("rainmaker", "Rainmaker"),
                            ("clam_blitz", "Clam Blitz"),
                            ("tower_control", "Tower Control"),
                            ("turf_war", "Turf War"),
                        ],
                        max_length=13,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("league_pair", "League Pair"),
                            ("league_team", "League Team"),
                            ("gachi", "Ranked"),
                            ("private", "Private"),
                            ("regular", "Turf War"),
                            ("fes_solo", "Splatfest Solo/Pro"),
                            ("fes_team", "Splatfest Team/Normal"),
                        ],
                        max_length=11,
                    ),
                ),
                ("stage", models.PositiveSmallIntegerField()),
                ("player_weapon", models.PositiveSmallIntegerField()),
                ("player_rank", models.CharField(max_length=4)),
                ("win", models.BooleanField()),
                ("has_disconnected_player", models.BooleanField()),
                ("time", models.DateTimeField()),
                ("player_user", models.ManyToManyField(to="two_battles.Player")),
            ],
        ),
    ]
