# Generated by Django 3.2 on 2021-04-22 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("two_battles", "0003_auto_20210422_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("League Pair", "Lp"),
                    ("League Team", "Lt"),
                    ("Ranked", "Rk"),
                    ("Private", "Pv"),
                    ("Turf War", "Rg"),
                    ("Splatfest Solo/Pro", "Fs"),
                    ("Splatfest Team/Normal", "Ft"),
                ],
                max_length=21,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="rule",
            field=models.CharField(
                choices=[
                    ("Splat Zones", "Sz"),
                    ("Rainmaker", "Rm"),
                    ("Clam Blitz", "Cb"),
                    ("Tower Control", "Tc"),
                    ("Turf War", "Tw"),
                ],
                max_length=13,
            ),
        ),
    ]
