# Generated by Django 3.2 on 2021-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0016_auto_20210423_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="my_team_count",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="battle",
            name="other_team_count",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
