# Generated by Django 3.2 on 2021-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0022_auto_20210425_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="player_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="player_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_assists",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_clothes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_clothes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_clothes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_clothes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_clothes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_deaths",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_headgear",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_headgear_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_headgear_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_headgear_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_headgear_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_kills",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_level_star",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_shoes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_shoes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_shoes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_shoes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_shoes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_specials",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_splatnet_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate1_weapon",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
