# Generated by Django 3.2 on 2021-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0027_alter_battle_match_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="teammate3_assists",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_clothes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_clothes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_clothes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_clothes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_clothes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_deaths",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_headgear",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_headgear_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_headgear_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_headgear_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_headgear_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_kills",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_level_star",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_rank",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_shoes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_shoes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_shoes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_shoes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_shoes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_specials",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_splatnet_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="teammate3_weapon",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
