# Generated by Django 3.2 on 2021-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0028_auto_20210425_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="opponent0_assists",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_clothes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_clothes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_clothes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_clothes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_clothes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_deaths",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_headgear",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_headgear_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_headgear_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_headgear_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_headgear_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_kills",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_level_star",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_rank",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_shoes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_shoes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_shoes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_shoes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_shoes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_specials",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_splatnet_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent0_weapon",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_assists",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_clothes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_clothes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_clothes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_clothes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_clothes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_deaths",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_headgear",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_headgear_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_headgear_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_headgear_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_headgear_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_kills",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_level_star",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_rank",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_shoes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_shoes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_shoes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_shoes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_shoes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_specials",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_splatnet_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent1_weapon",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_assists",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_clothes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_clothes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_clothes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_clothes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_clothes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_deaths",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_headgear",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_headgear_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_headgear_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_headgear_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_headgear_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_kills",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_level_star",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_rank",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_shoes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_shoes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_shoes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_shoes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_shoes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_specials",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_splatnet_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent2_weapon",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_assists",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_clothes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_clothes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_clothes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_clothes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_clothes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_deaths",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_gender",
            field=models.CharField(
                choices=[("girl", "Female"), ("boy", "Male")], max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_headgear",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_headgear_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_headgear_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_headgear_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_headgear_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_kills",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_level",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_level_star",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_name",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_rank",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_shoes",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_shoes_main",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_shoes_sub0",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_shoes_sub1",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_shoes_sub2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_specials",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_species",
            field=models.CharField(
                choices=[("inklings", "Inkling"), ("octolings", "Octoling")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_splatnet_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="opponent3_weapon",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
