# Generated by Django 3.2 on 2021-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0037_alter_battle_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="battle_number",
            field=models.CharField(
                max_length=255, null=True, verbose_name="SplatNet Battle Number"
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("league_pair", "League Pair"),
                    ("league_team", "League Team"),
                    ("gachi", "Ranked"),
                    ("private", "Private"),
                    ("turf_war", "Turf War"),
                    ("fes_solo", "Splatfest Solo/Pro"),
                    ("fes_team", "Splatfest Team/Normal"),
                    ("fest", "Splatfest"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="stage",
            field=models.CharField(
                choices=[
                    ("0", "The Reef"),
                    ("1", "Musselforge Fitness"),
                    ("2", "Starfish Mainstage"),
                    ("3", "Sturgeon Shipyard"),
                    ("4", "Inkblot Art Academy"),
                    ("5", "Humpback Pump Track"),
                    ("6", "Manta Maria"),
                    ("7", "Port Mackerel"),
                    ("8", "Moray Towers"),
                    ("9", "Snapper Canal"),
                    ("10", "Kelp Dome"),
                    ("11", "Blackbelly Skatepark"),
                    ("12", "Shellendorf Institute"),
                    ("13", "MakoMart"),
                    ("14", "Walleye Warehouse"),
                    ("15", "Arowana Mall"),
                    ("16", "Camp Triggerfish"),
                    ("17", "Piranha Pit"),
                    ("18", "Goby Arena"),
                    ("19", "New Albacore Hotel"),
                    ("20", "Wahoo World"),
                    ("21", "Ancho-V Games"),
                    ("22", "Skipper Pavillion"),
                    ("109", "Zappy Longshocking"),
                    ("112", "The Switches"),
                    ("113", "Sweet Valley Tentacles"),
                    ("115", "Railway Chillin'"),
                    ("118", "Flooders in the Attic"),
                    ("119", "The Splat in Our Zones"),
                    ("120", "The Ink is Spreading"),
                    ("121", "Bridge to Tentaswitchia"),
                    ("122", "The Chronicles of Rolonium"),
                    ("9999", "Shifty Station"),
                ],
                max_length=4,
            ),
        ),
    ]
