# Generated by Django 3.2.2 on 2021-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0042_alter_battle_player_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="splatnet_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="stat_ink_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
