# Generated by Django 3.2 on 2021-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="battle_number",
            field=models.CharField(
                default="4488", max_length=255, verbose_name="SplatNet Battle Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battle",
            name="player_result_player_weapon_special",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="Special"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battle",
            name="player_result_player_weapon_sub",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Sub Weapon"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battle",
            name="tag_id",
            field=models.CharField(blank=True, max_length=11, verbose_name="Team ID"),
        ),
        migrations.AddField(
            model_name="battle",
            name="win_meter",
            field=models.IntegerField(
                blank=True, default=None, verbose_name="Freshness", null=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="battle",
            name="time",
            field=models.PositiveIntegerField(),
        ),
    ]
