# Generated by Django 3.2 on 2021-04-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0004_auto_20210422_1852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battle",
            name="player_rank_after",
        ),
        migrations.AlterField(
            model_name="battle",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("league_pair", "League Pair"),
                    ("league_team", "League Team"),
                    ("gachi", "Ranked"),
                    ("private", "Private"),
                    ("regular", "Turf War"),
                    ("fes_solo", "Splatfest Solo/Pro"),
                    ("fes_team", "Splatfest Team/Normal"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="player_rank",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="battle",
            name="rule",
            field=models.CharField(
                choices=[
                    ("splat_zones", "Splat Zones"),
                    ("rainmaker", "Rainmaker"),
                    ("clam_blitz", "Clam Blitz"),
                    ("tower_control", "Tower Control"),
                    ("turf_war", "Turf War"),
                ],
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="splatnet_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="splatNet 2 JSON file"
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="stat_ink_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="stat.ink JSON file"
            ),
        ),
    ]
