# Generated by Django 3.2 on 2021-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0006_auto_20210423_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="player_rank",
            field=models.IntegerField(),
        ),
    ]
