# Generated by Django 3.2 on 2021-04-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0008_alter_battle_win"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="player_rank",
            field=models.IntegerField(null=True),
        ),
    ]
