# Generated by Django 3.2 on 2021-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0014_alter_battle_elapsed_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="game_paint_point",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
