# Generated by Django 3.2 on 2021-04-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_battles', '0019_auto_20210425_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='splatfest_title',
            new_name='player_splatfest_title',
        ),
    ]
