# Generated by Django 3.2 on 2021-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_battles', '0020_rename_splatfest_title_battle_player_splatfest_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='x_power',
            new_name='player_x_power',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_result_player_weapon_special',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_result_player_weapon_sub',
        ),
        migrations.AddField(
            model_name='battle',
            name='player_clothes',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_clothes_main',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_clothes_sub0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_clothes_sub1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_clothes_sub2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_headgear',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_headgear_main',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_headgear_sub0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_headgear_sub1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_headgear_sub2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_shoes',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_shoes_main',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_shoes_sub0',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_shoes_sub1',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_shoes_sub2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
