# Generated by Django 3.2 on 2021-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0024_auto_20210425_1301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="teammate1_rank",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
