# Generated by Django 3.2 on 2021-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0034_auto_20210426_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="image_gear",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="battle",
            name="image_result",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
