# Generated by Django 3.2.3 on 2021-05-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_salmon', '0004_auto_20210514_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='player_power_eggs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='player_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_salmon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='teammate0_power_eggs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='teammate1_power_eggs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='teammate2_power_eggs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='player_title',
            field=models.CharField(choices=[('1', 'Apprentice'), ('2', 'Part Timer'), ('3', 'Go Getter'), ('4', 'Overachiever'), ('5', 'Profreshional')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='teammate0_title',
            field=models.CharField(choices=[('1', 'Apprentice'), ('2', 'Part Timer'), ('3', 'Go Getter'), ('4', 'Overachiever'), ('5', 'Profreshional')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='teammate1_title',
            field=models.CharField(choices=[('1', 'Apprentice'), ('2', 'Part Timer'), ('3', 'Go Getter'), ('4', 'Overachiever'), ('5', 'Profreshional')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='teammate2_title',
            field=models.CharField(choices=[('1', 'Apprentice'), ('2', 'Part Timer'), ('3', 'Go Getter'), ('4', 'Overachiever'), ('5', 'Profreshional')], max_length=1, null=True),
        ),
    ]
