# Generated by Django 3.2.3 on 2021-05-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_salmon', '0005_auto_20210515_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='schdeule_endtime',
            new_name='schedule_endtime',
        ),
    ]
