# Generated by Django 3.2.3 on 2021-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_salmon", "0008_auto_20210515_1010"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("player_id", "job_id"), name="unique-two-shift"
            ),
        ),
    ]
