# Generated by Django 3.2 on 2021-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0010_alter_battle_has_disconnected_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="time",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
