# Generated by Django 3.2 on 2021-04-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0018_alter_battle_player_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="battle",
            old_name="assists",
            new_name="player_assists",
        ),
        migrations.RenameField(
            model_name="battle",
            old_name="deaths",
            new_name="player_deaths",
        ),
        migrations.RenameField(
            model_name="battle",
            old_name="game_paint_point",
            new_name="player_game_paint_point",
        ),
        migrations.RenameField(
            model_name="battle",
            old_name="kills",
            new_name="player_kills",
        ),
        migrations.RenameField(
            model_name="battle",
            old_name="level",
            new_name="player_level",
        ),
        migrations.RenameField(
            model_name="battle",
            old_name="specials",
            new_name="player_specials",
        ),
    ]
