# Generated by Django 3.2 on 2021-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0026_auto_20210425_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("league_pair", "League Pair"),
                    ("league_team", "League Team"),
                    ("gachi", "Ranked"),
                    ("private", "Private"),
                    ("turf_war", "Turf War"),
                    ("fes_solo", "Splatfest Solo/Pro"),
                    ("fes_team", "Splatfest Team/Normal"),
                ],
                max_length=11,
            ),
        ),
    ]
