# Generated by Django 3.2 on 2021-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0031_auto_20210425_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="player_rank",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "C-"),
                    (1, "C"),
                    (2, "C+"),
                    (3, "B-"),
                    (4, "B"),
                    (5, "B+"),
                    (6, "A-"),
                    (7, "A"),
                    (8, "A+"),
                    (9, "S"),
                    (10, "S+0"),
                    (11, "S+1"),
                    (12, "S+2"),
                ],
                null=True,
            ),
        ),
    ]
