# Generated by Django 3.2 on 2021-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("two_battles", "0036_auto_20210428_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="stage",
            field=models.CharField(
                choices=[
                    ("0", "The Reef"),
                    ("1", "Musselforge Fitness"),
                    ("2", "Starfish Mainstage"),
                    ("3", "Sturgeon Shipyard"),
                    ("4", "Inkblot Art Academy"),
                    ("5", "Humpback Pump Track"),
                    ("6", "Manta Maria"),
                    ("7", "Port Mackerel"),
                    ("8", "Moray Towers"),
                    ("9", "Snapper Canal"),
                    ("10", "Kelp Dome"),
                    ("11", "Blackbelly Skatepark"),
                    ("12", "Shellendorf Institute"),
                    ("13", "MakoMart"),
                    ("14", "Walleye Warehouse"),
                    ("15", "Arowana Mall"),
                    ("16", "Camp Triggerfish"),
                    ("17", "Piranha Pit"),
                    ("18", "Goby Arena"),
                    ("19", "New Albacore Hotel"),
                    ("20", "Wahoo World"),
                    ("21", "Ancho-V Games"),
                    ("22", "Skipper Pavillion"),
                    ("115", "Railway Chillin'"),
                    ("9999", "Shifty Station"),
                ],
                max_length=4,
            ),
        ),
    ]
